server:
  port: 8761

spring:
  application:
    name: eureka-server
  main:
    banner-mode: off
  profiles:
    default: prod
    group:
      local: local
      dev: dev
      prod: prod

eureka:
  client:
    register-with-eureka: false # ?? ??? ?????? ???? ??? ?? ??
    fetch-registry: false # ??????? eureka ???? eureka ????? ??? ???? ??? ??

# ===============================
# = logback
# ===============================
logging:
  config: classpath:logback-spring.xml
